name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  lint:
    strategy:
      matrix:
        deno_version: ["v1.24.3"]
        os: [ubuntu-latest]
    name: deno lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: run lint
        run: deno lint
  test:
    strategy:
      matrix:
        runner:
          - windows-2022
          - macos-12
          - ubuntu-22.04
        version:
          - "v1.24.3"
        host_version:
          - vim: "v8.2.3452"
            nvim: "v0.6.0"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "${{ matrix.version }}"
      - uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_type: "Vim"
          vim_version: "${{ matrix.host_version.vim }}"
          download: "never"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM}
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable_path }}
      - uses: thinca/action-setup-vim@v1
        id: nvim
        with:
          vim_type: "Neovim"
          vim_version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM}
        env:
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable_path }}
      - name: Clone denops
        id: denops
        run: |
          git clone https://github.com/vim-denops/denops.vim $HOME/denops.vim
          echo "::set-output name=path::$HOME/denops.vim"
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install expat
          sudo apt install libxml2-dev
          sudo apt install pkg-config libasound2-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb-composite0-dev
      - name: Test
        run: |
          make test
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable_path }}
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable_path }}
          DENOPS_PATH: ${{ steps.denops.outputs.path }}
        timeout-minutes: 5
